#
# lPractice made by LyraGames
#

MONGODB:
  URI-MODE: false
  DATABASE: "lpractice"
  NORMAL:
    HOST: "127.0.0.1"
    PORT: 27017
    AUTH:
      ENABLED: false
      USERNAME: "user"
      PASSWORD: "pass"
      AUTH-DATABASE: "admin"
  URI:
    CONNECTION-STRING: ""


SPAWN: ""

COLOR:
  PRIMARY: "YELLOW"
  SECONDARY: "GREEN"