#
# lPractice made by LyraGames
#

MONGO:
  URI-MODE: false
  NORMAL:
    HOST: "127.0.0.1"
    PORT: 27017
    DATABASE: "lpractice"
    AUTH:
      ENABLED: false
      USERNAME: "user"
      PASSWORD: "pass"
      AUTH-DATABASE: "admin"
  URI:
    CONNECTION-STRING: ""
    DATABASE-NAME: ""


spawn: ""